In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('/content/winequality-red.csv')

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [4]:
X = dataset.iloc[: , 1:-1].values
y = dataset.iloc[:, -1].values

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X ,y, test_size=0.20)

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
sc = StandardScaler()

In [9]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [11]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel= 'rbf')

In [12]:
l_cla.fit(X_train, y_train)
k_cla.fit(X_train, y_train)
d_cla.fit(X_train, y_train)
r_cla.fit(X_train, y_train)
s_cla.fit(X_train, y_train)
ks_cla.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [13]:
l_pred = l_cla.predict(X_test)
k_pred = k_cla.predict(X_test)
d_pred = d_cla.predict(X_test)
r_pred = r_cla.predict(X_test)
s_pred = s_cla.predict(X_test)
ks_pred = ks_cla.predict(X_test)

In [14]:
from sklearn.metrics import confusion_matrix

In [15]:
l_c = confusion_matrix(y_test, l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)

In [16]:
l_c

array([[ 0,  1,  1,  0,  0,  0],
       [ 0,  0,  8,  3,  0,  0],
       [ 0,  0, 93, 32,  1,  0],
       [ 0,  0, 37, 93,  8,  0],
       [ 0,  0,  0, 28, 12,  0],
       [ 0,  0,  0,  2,  1,  0]])

In [17]:
k_c

array([[ 0,  1,  1,  0,  0,  0],
       [ 0,  0,  5,  6,  0,  0],
       [ 0,  1, 87, 37,  1,  0],
       [ 0,  0, 40, 87, 11,  0],
       [ 0,  0,  6, 21, 13,  0],
       [ 0,  0,  0,  1,  2,  0]])

In [18]:
d_c

array([[ 0,  2,  0,  0,  0,  0],
       [ 0,  1,  4,  6,  0,  0],
       [ 0,  7, 90, 28,  1,  0],
       [ 0,  0, 34, 90,  9,  5],
       [ 0,  1,  4,  9, 24,  2],
       [ 0,  0,  1,  2,  0,  0]])

In [19]:
r_c

array([[  0,   0,   2,   0,   0,   0],
       [  0,   0,   8,   3,   0,   0],
       [  0,   0, 100,  26,   0,   0],
       [  0,   0,  21, 103,  14,   0],
       [  0,   0,   1,  21,  18,   0],
       [  0,   0,   0,   3,   0,   0]])

In [20]:
s_c

array([[ 0,  0,  2,  0,  0,  0],
       [ 0,  0,  8,  3,  0,  0],
       [ 0,  0, 91, 35,  0,  0],
       [ 0,  0, 42, 96,  0,  0],
       [ 0,  0,  0, 40,  0,  0],
       [ 0,  0,  0,  3,  0,  0]])

In [21]:
ks_c

array([[ 0,  0,  2,  0,  0,  0],
       [ 0,  0,  9,  2,  0,  0],
       [ 0,  0, 93, 32,  1,  0],
       [ 0,  0, 36, 94,  8,  0],
       [ 0,  0,  1, 28, 11,  0],
       [ 0,  0,  0,  3,  0,  0]])

In [22]:
from sklearn.metrics import accuracy_score

In [23]:
l_a = accuracy_score(y_test, l_pred)
k_a = accuracy_score(y_test, k_pred)
d_a = accuracy_score(y_test, d_pred)
r_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

In [24]:
print('Logistic Regression: ' + str(l_a) + '\nKNN: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(l_a))

Logistic Regression: 0.61875
KNN: 0.584375
Decision Tree: 0.640625
Random Forest: 0.690625
Linear SVC: 0.584375
Kernel SVC: 0.61875


##conclusion
since random forest accuracy is high we are condidering this
Thank You
SABHA ZAINAB
